== Changes in the original project

In this fork I have changed only the code in the complete folder to add link:http://springfox.github.io/springfox/[Springfox] to document the API using link:http://swagger.io/[Swagger 2].

== How to see the example in action

Get the application running:
----
mvn spring-boot:run
----

Call the API operation on your browser:
----
http://localhost:8080/springfox/api/greeting
----

and see the response:

[source,json]
----
{
  "id": 1,
  "content": "Hello, World!"
}
----

You can customize the greeting with an optional `name` parameter in the query string:

----
http://localhost:8080/springfox/api/greeting?name=User
----

The `name` parameter value overrides the default value of "World" and is reflected in the response:

[source,json]
----
{
  "id": 1,
  "content":"Hello, User!"
}
----

== Test the call to Swagger UI

Now that the service is up, visit http://localhost:8080/springfox, where you see the UI

Try to click on the *greeting-controller* link. It will expand and show the operations and the possible HTTP methods.

Click again on the */api/greeting* and it will expand a little more and show details about the endpoint.

It's also possible to invoke the endpoint clicking on the *"Try it out!"* button.